#!/bin/bash
#
# Log uptime using uptime.

log_file="/var/log/loguptime/log"

uptime --since >> $log_file
echo -n "     until" >> $log_file
uptime >> $log_file
echo >> $log_file
echo "--------------------------------------------------------------------------------" >> $log_file
echo >> $log_file
